<?php

namespace App\Rules;

use Illuminate\Contracts\Validation\Rule;

class BarrioValido implements Rule
{
    protected array $barriosValidos = [
        'Granizal',
        'Populares',
        'Moscú N°2',
        'Villa Guadalupe',
        'El Compromiso',
        'Santo Domingo Sabio N°1',
        'San Pablo',
        'Carpinelo',
        'Aldea Pablo VI',
        'Santo Domingo Sabio N°2',
        'La Avanzada',
        'La Esperanza N°2',
        'Pablo VI',
        'La Francia',
        'La frontera',
        'Andalucía',
        'Santa Cruz',
        'La Rosa',
        'La Isla',
        'Villa Socorro',
        'Moscú No1',
        'Villa Niza',
        'El playón de los comuneros',
        'El Raizal',
        'El Pomar',
        'La Salle',
        'Las Granjas',
        'Santa Inés',
        'Campo Valdés No 1',
        'San José de la Cima No 1',
        'San José de la Cima No 2',
        'La Cruz',
        'Oriente',
        'Versalles No 1',
        'Versalles No 2',
        'Manrique oriental',
        'Manrique Central No 2',
        'Maria Cano - Carambolas',
        'Berlín',
        'Sevilla',
        'Brasilia',
        'San Isidro',
        'Palermo',
        'Moravia',
        'Las Esmeraldas',
        'Aranjuez',
        'Miranda',
        'La Piñuela',
        'San Pedro',
        'Manrique central No 1',
        'Bermejal – Los Álamos',
        'Tejelo',
        'Boyacá',
        'Las Brisas',
        'Toscana',
        'Florencia',
        'Belalcázar',
        'Héctor Abad Gómez',
        'Castilla',
        'Caribe',
        'Girardot',
        'El Progreso',
        'Tricentenario',
        'Alfonso López',
        'Francisco Antonio Zea',
        'Santander',
        'Pedregal',
        'La Esperanza',
        'San Martín de Porres',
        'Doce de Octubre N°1',
        'Doce de Octubre N°2',
        'Picacho',
        'El Triunfo',
        'Kennedy',
        'Picachito',
        'Mirador del Doce',
        'El Progreso N°2',
        'Pilarica',
        'Altamira',
        'Córdoba',
        'San Germán',
        'Cerro el Volador',
        'Bosques de San Pablo',
        'B. Facultad de Minas U.',
        'Nacional',
        'Robledo',
        'Pajarito',
        'Monteclaro',
        'El Cucaracho',
        'Fuente Clara',
        'Olaya Herrera',
        'Santa Margarita',
        'Nueva Villa de Iguaná',
        'Villa Flora',
        'Palenque',
        'Aures No. 1',
        'Aures No. 2',
        'El Diamante',
        'López de Meza',
        'Bello Horizonte',
        'La Ladera',
        'Llanaditas',
        'La Mansión',
        'San Miguel',
        'Villa Hermosa',
        'Batallón Girardot',
        'Villa Tina',
        'La Sierra',
        'Villa Liliam',
        'Los Mangos',
        'San Antonio',
        'Las Estancias',
        'Enciso',
        'Sucre',
        'El Pinal',
        'La Libertad',
        'Villa Turbay',
        '13 de Noviembre',
        'Cataluña',
        'Miraflores',
        'Juan Pablo II',
        'Buenos Aires',
        'Barrio Caicedo',
        'Barrios de Jesús',
        'Ocho de Marzo',
        'Bomboná No.2',
        'La Milagrosa',
        'El Salvador',
        'Gerona',
        'Loreto',
        'Asomadera No.1',
        'Asomadera No.2',
        'Asomadera No.3',
        'Los Cerros El Vergel',
        'Alejandro Echavarría',
        'Prado',
        'Guayaquil',
        'San Benito',
        'El Chagualo',
        'Calle Nueva',
        'Estación Villa',
        'Boston',
        'San Diego',
        'Las Palmas',
        'Villa Nueva',
        'Los Ángeles',
        'Barrio Colón',
        'La Candelaria',
        'Bomboná No.1',
        'Jesús Nazareno',
        'Corazón de Jesús',
        'Perpetuo Socorro',
        'Lorena',
        'Estadio',
        'Los Colores',
        'Las Acacias',
        'La Castellana',
        'Florida Nueva',
        'El Velódromo',
        'Cuarta Brigada',
        'Laureles',
        'Naranjal',
        'Bolivariana',
        'San Joaquín',
        'Suramericana',
        'Carlos E. Restrepo',
        'Los Conquistadores',
        'Ferrini',
        'Calazans',
        'Los Pinos',
        'El Danubio',
        'La América',
        'La Floresta',
        'Santa Lucia',
        'Cristóbal',
        'Santa Mónica',
        'Simón Bolivar',
        'Santa Teresita',
        'Campo Alegre',
        'Calazans Parte Alta',
        'Juan XXIII',
        'El Pesebre',
        'Blanquizal',
        'La Pradera',
        'Los Alcázares',
        'Metropolitano',
        'El Socorro',
        'El Corazón',
        'Veinte de Julio',
        'Antonio Nariño',
        'San Javier n.º 1',
        'San Javier n.º 2',
        'Betania',
        'El Salado',
        'Belencito',
        'Eduardo Santos',
        'Santa Rosa de Lima',
        'Nuevos Conquistadores',
        'Las Independencias',
        'El Tesoro',
        'Castropol',
        'La Florida',
        'San Lucas',
        'Patio Bonito',
        'Los Naranjos',
        'La Aguacatala',
        'Manila',
        'Astorga',
        'Lalinde',
        'El Castillo',
        'Alejandría',
        'El Poblado',
        'Villa Carlota',
        'Los Balsos Nº 1',
        'Las Lomas Nº 1',
        'Los Balsos Nº 2',
        'Barrio Colombia',
        'Las Lomas Nº 2',
        'Altos del Poblado',
        'El Diamante Nº 2',
        'Santa María de Los Ángeles',
        'Tenche',
        'Trinidad',
        'Santa Fe',
        'Guayabal',
        'La Colina',
        'Campo Amor',
        'Cristo Rey',
        'La Mota',
        'Altavista',
        'La Gloria',
        'La Palma',
        'Los Alpes',
        'Las Violetas',
        'Las Mercedes',
        'Miravalle',
        'Fátima',
        'Rosales',
        'Belén',
        'Granada',
        'El Rincón',
        'Las Playas',
        'San Bernardo',
        'Cerro Nutibara',
        'Diego Echavarría',
        'La Hondonada',
        'La Loma de los Bernal',
        'Nueva Villa de Aburra',
        'El Nogal - Los Almendros',
    ];

    public function passes($attribute, $value): bool
    {
        return in_array($value, $this->barriosValidos, true);
    }

    public function message(): string
    {
        return 'El barrio seleccionado no es válido.';
    }
}
